In [ ]:
import numpy as np
import pandas as pd
import tushare as ts

__List of data to join:__

a) China - GDP Growth Rate (quarterly)

b) China - CPI (monthly)

c) China - PPI

d) China - saving interest rate

e) China - loan interest rate

f) China - RRR

g) China - Money supply

h) U.S. - SP500

i) U.S. - U.S. stock

j) U.S. - Trump Tweets

In [6]:
# Generate a series of dates from 2013/01/01 to 2018/11/30

dates = pd.date_range(start='1/1/2013', end='11/30/2018')

In [11]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10',
               ...
               '2018-11-21', '2018-11-22', '2018-11-23', '2018-11-24',
               '2018-11-25', '2018-11-26', '2018-11-27', '2018-11-28',
               '2018-11-29', '2018-11-30'],
              dtype='datetime64[ns]', length=2160, freq='D')

In [27]:
dates_series = pd.Series(dates)

In [33]:
dates_series = dates_series.astype(str)

In [35]:
dates_df = pd.DataFrame(data=dates_series, columns=['Date'])

In [8]:
# China - GDP Growth Rate

gdp_growth = pd.read_csv('China Quarterly GDP Growth Rate 2011-2018.csv')

In [12]:
def quarter_to_date(series):
    temp = series.split('-')
    dic = {'Q1': '01-01', 'Q2': '04-01', 'Q3': '07-01', 'Q4': '10-01'}
    return temp[0] + '-' + dic[temp[1]]

In [14]:
date_gdp_growth = gdp_growth.TIME.apply(quarter_to_date)

In [15]:
gdp_growth['Date'] = date_gdp_growth

In [17]:
gdp_growth.drop(columns=['TIME'], inplace=True)

In [22]:
gdp_growth.rename(index=str, columns={'Value':'GDP Growth Rate'}, inplace=True)

In [39]:
final = dates_df.merge(gdp_growth, how='left', on='Date')

In [1]:
# China - CPI

cpi = ts.get_cpi()

In [42]:
def month_to_date(series):
    temp = series.split('.')
    if len(temp[1]) == 1:
        return temp[0] + '-' + '0' + temp[1] + '-01'
    else:
        return temp[0] + '-' + temp[1] + '-01'

In [43]:
date_cpi = cpi.month.apply(month_to_date)

In [45]:
cpi['Date'] = date_cpi

In [46]:
cpi.drop(columns=['month'], inplace=True)

In [48]:
cpi.rename(index=str, columns={'cpi': 'CPI'}, inplace=True)

In [49]:
final = final.merge(cpi, how='left', on='Date')

In [57]:
# China - PPI

ppi = ts.get_ppi()

In [58]:
dates_ppi = ppi.month.apply(month_to_date)
ppi['Date'] = dates_ppi
ppi.drop(columns='month', inplace=True)

In [59]:
ppi.columns = ['PPI_' + name for name in ppi.columns]

In [61]:
final = final.merge(ppi, how='left', left_on='Date', right_on='PPI_Date')

In [64]:
final.drop(columns=['PPI_Date'], inplace=True)

In [67]:
# China - Savings Interest Rate

deposit_rate = ts.get_deposit_rate()

In [68]:
deposit_rate

           date            deposit_type   rate
0    2015-10-24                定活两便(定期)     --
1    2015-10-24            定期存款整存整取(半年)   1.30
2    2015-10-24            定期存款整存整取(二年)   2.10
3    2015-10-24           定期存款整存整取(三个月)   1.10
4    2015-10-24            定期存款整存整取(三年)   2.75
5    2015-10-24            定期存款整存整取(五年)     --
6    2015-10-24            定期存款整存整取(一年)   1.50
7    2015-10-24               活期存款(不定期)   0.35
8    2015-10-24  零存整取、整存零取、存本取息定期存款(三年)   1.30
9    2015-10-24  零存整取、整存零取、存本取息定期存款(五年)     --
10   2015-10-24  零存整取、整存零取、存本取息定期存款(一年)   1.10
11   2015-10-24                通知存款(七天)   1.35
12   2015-10-24                通知存款(一天)   0.80
13   2015-10-24                协定存款(定期)   1.15
14   2015-08-26                定活两便(定期)     --
15   2015-08-26            定期存款整存整取(半年)   1.55
16   2015-08-26            定期存款整存整取(二年)   2.35
17   2015-08-26           定期存款整存整取(三个月)   1.35
18   2015-08-26            定期存款整存整取(三年)   3.00
19   2015-08-26            定期存款整存整取(五年)     --
20   2015-08-26            定期存款整存整取(一年)   1.75
21   2015-08-26               活期存款(不定期)   0.35
22   2015-08-26  零存整取、整存零取、存本取息定期存款(三年)   1.55
23   2015-08-26  零存整取、整存零取、存本取息定期存款(五年)     --
24   2015-08-26  零存整取、整存零取、存本取息定期存款(一年)   1.35
25   2015-08-26                通知存款(七天)   1.35
26   2015-08-26                通知存款(一天)   0.80
27   2015-08-26                协定存款(定期)   1.15
28   2015-06-28                定活两便(定期)     --
29   2015-06-28            定期存款整存整取(半年)   1.80
..          ...                     ...    ...
516  1990-08-21                通知存款(一天)     --
517  1990-08-21                协定存款(定期)     --
518  1990-04-15                定活两便(定期)     --
519  1990-04-15            定期存款整存整取(半年)   7.74
520  1990-04-15            定期存款整存整取(二年)  11.00
521  1990-04-15           定期存款整存整取(三个月)   6.30
522  1990-04-15            定期存款整存整取(三年)  11.88
523  1990-04-15            定期存款整存整取(五年)  13.68
524  1990-04-15            定期存款整存整取(一年)  10.08
525  1990-04-15               活期存款(不定期)   2.88
526  1990-04-15  零存整取、整存零取、存本取息定期存款(三年)     --
527  1990-04-15  零存整取、整存零取、存本取息定期存款(五年)     --
528  1990-04-15  零存整取、整存零取、存本取息定期存款(一年)     --
529  1990-04-15                通知存款(七天)     --
530  1990-04-15                通知存款(一天)     --
531  1990-04-15                协定存款(定期)     --
532  1989-02-01                定活两便(定期)     --
533  1989-02-01            定期存款整存整取(半年)   9.00
534  1989-02-01            定期存款整存整取(二年)  12.20
535  1989-02-01           定期存款整存整取(三个月)   7.56
536  1989-02-01            定期存款整存整取(三年)  13.14
537  1989-02-01            定期存款整存整取(五年)  14.94
538  1989-02-01            定期存款整存整取(一年)  11.34
539  1989-02-01               活期存款(不定期)   2.88
540  1989-02-01  零存整取、整存零取、存本取息定期存款(三年)     --
541  1989-02-01  零存整取、整存零取、存本取息定期存款(五年)     --
542  1989-02-01  零存整取、整存零取、存本取息定期存款(一年)     --
543  1989-02-01                通知存款(七天)     --
544  1989-02-01                通知存款(一天)     --
545  1989-02-01                协定存款(定期)     --

[546 rows x 3 columns]

In [69]:
deposit_rate_pivoted = deposit_rate.pivot(index='date', columns='deposit_type', values='rate')

In [89]:
final = final.merge(deposit_rate_pivoted, how='left', left_on='Date', right_index=True)

In [71]:
# China - Loan Interest Rate

loan_rate = ts.get_loan_rate()
loan_rate

           date            loan_type   rate
0    2015-10-24          短期贷款(六个月以内)   4.35
1    2015-10-24         短期贷款(六个月至一年)   4.35
2    2015-10-24          中长期贷款(三至五年)   4.75
3    2015-10-24          中长期贷款(五年以上)   4.90
4    2015-10-24          中长期贷款(一至三年)   4.75
5    2015-10-24               贴现(贴现)     --
6    2015-10-24         优惠贷款(扶贫贴息贷款)     --
7    2015-10-24     优惠贷款(老少边穷发展经济贷款)     --
8    2015-10-24     优惠贷款(民政部门福利工厂贷款)     --
9    2015-10-24  优惠贷款(民族贸易及民族用品生产贷款)     --
10   2015-10-24       优惠贷款(贫困县办工业贷款)     --
11   2015-10-24      个人住房商业贷款(六个月以内)   3.92
12   2015-10-24     个人住房商业贷款(六个月至一年)   3.92
13   2015-10-24       个人住房商业贷款(三至五年)   4.28
14   2015-10-24       个人住房商业贷款(五年以上)   4.41
15   2015-10-24       个人住房商业贷款(一至三年)   4.28
16   2015-10-24      个人住房公积金贷款(五年以上)   3.25
17   2015-10-24      个人住房公积金贷款(五年以下)   2.75
18   2015-09-06            再贴现(再贴现率)   2.25
19   2015-08-26          短期贷款(六个月以内)   4.60
20   2015-08-26         短期贷款(六个月至一年)   4.60
21   2015-08-26          中长期贷款(三至五年)   5.00
22   2015-08-26          中长期贷款(五年以上)   5.15
23   2015-08-26          中长期贷款(一至三年)   5.00
24   2015-08-26               贴现(贴现)     --
25   2015-08-26         优惠贷款(扶贫贴息贷款)     --
26   2015-08-26     优惠贷款(老少边穷发展经济贷款)     --
27   2015-08-26     优惠贷款(民政部门福利工厂贷款)     --
28   2015-08-26  优惠贷款(民族贸易及民族用品生产贷款)     --
29   2015-08-26       优惠贷款(贫困县办工业贷款)     --
..          ...                  ...    ...
770  1993-05-15      个人住房公积金贷款(五年以上)     --
771  1993-05-15      个人住房公积金贷款(五年以下)     --
772  1993-05-12         特种贷款(特种贷款利率)  11.25
773  1991-04-21          短期贷款(六个月以内)   8.10
774  1991-04-21         短期贷款(六个月至一年)   8.64
775  1991-04-21          中长期贷款(三至五年)   9.54
776  1991-04-21          中长期贷款(五年以上)   9.72
777  1991-04-21          中长期贷款(一至三年)   9.00
778  1991-04-21               贴现(贴现)     --
779  1991-04-21         优惠贷款(扶贫贴息贷款)   2.88
780  1991-04-21     优惠贷款(老少边穷发展经济贷款)   5.76
781  1991-04-21     优惠贷款(民政部门福利工厂贷款)   7.20
782  1991-04-21  优惠贷款(民族贸易及民族用品生产贷款)   5.76
783  1991-04-21       优惠贷款(贫困县办工业贷款)   5.76
784  1991-04-21      个人住房商业贷款(六个月以内)   7.29
785  1991-04-21     个人住房商业贷款(六个月至一年)   7.78
786  1991-04-21       个人住房商业贷款(三至五年)   8.59
787  1991-04-21       个人住房商业贷款(五年以上)   8.75
788  1991-04-21       个人住房商业贷款(一至三年)   8.10
789  1991-04-21      个人住房公积金贷款(五年以上)     --
790  1991-04-21      个人住房公积金贷款(五年以下)     --
791  1991-04-21         特种贷款(特种贷款利率)   9.72
792  1990-08-21          短期贷款(六个月以内)   8.64
793  1990-08-21         短期贷款(六个月至一年)   9.36
794  1990-08-21          中长期贷款(三至五年)  10.80
795  1990-08-21          中长期贷款(五年以上)  11.16
796  1990-08-21          中长期贷款(一至三年)  10.08
797  1990-08-21               贴现(贴现)     --
798  1990-08-21         优惠贷款(扶贫贴息贷款)     --
799  1990-08-21     优惠贷款(老少边穷发展经济贷款)     --

[800 rows x 3 columns]

In [72]:
loan_rate_pivoted = loan_rate.pivot(index='date', columns='loan_type', values='rate')
loan_rate_pivoted

loan_type,个人住房公积金贷款(五年以上),个人住房公积金贷款(五年以下),个人住房商业贷款(一至三年),个人住房商业贷款(一至六个月（含六个月）),个人住房商业贷款(三至五年),个人住房商业贷款(五年以上),个人住房商业贷款(六个月以内),个人住房商业贷款(六个月至一年),中长期贷款(一至三年),中长期贷款(三至五年),...,优惠贷款(贫困县办工业贷款),优惠贷款(银行系统印制企业基建储备贷款),再贴现(再贴现率),流动资产贷款(流动资产贷款利率),特种贷款(特种贷款利率),短期贷款(六个月以内),短期贷款(六个月至一年),罚息(挤占挪用贷款),罚息(逾期贷款),贴现(贴现)
date,,,,,,,,,,,,,,,,,,,,,
1990-08-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.08,10.80,...,NaN,NaN,NaN,NaN,NaN,8.64,9.36,NaN,NaN,--
1991-04-21,--,--,8.10,NaN,8.59,8.75,7.29,7.78,9.00,9.54,...,5.76,NaN,NaN,NaN,9.72,8.10,8.64,NaN,NaN,--
1993-05-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,11.25,NaN,NaN,NaN,NaN,NaN
1993-05-15,--,--,9.72,NaN,10.85,11.02,7.94,8.42,10.80,12.06,...,6.48,NaN,NaN,NaN,NaN,8.82,9.36,NaN,NaN,--
1993-07-11,--,--,11.02,NaN,12.47,12.64,8.10,9.88,12.24,13.86,...,6.48,NaN,NaN,NaN,NaN,9.00,10.98,NaN,NaN,--
1995-01-01,--,--,11.66,NaN,13.12,13.28,8.10,9.88,12.96,14.58,...,6.48,NaN,NaN,NaN,NaN,9.00,10.98,NaN,NaN,--
1995-07-01,--,--,12.15,NaN,13.61,13.77,9.07,10.85,13.50,15.12,...,9.36,NaN,NaN,NaN,NaN,10.08,12.06,NaN,NaN,--
1996-05-01,--,--,11.83,NaN,13.45,13.61,8.75,9.88,13.14,14.94,...,8.10,NaN,--,NaN,NaN,9.72,10.98,NaN,NaN,--
1996-08-23,--,--,9.88,NaN,10.53,11.18,8.26,9.07,10.98,11.70,...,7.20,NaN,--,NaN,NaN,9.18,10.08,NaN,NaN,--
1997-10-23,--,--,8.42,NaN,8.91,9.48,6.88,7.78,9.36,9.90,...,5.76,NaN,--,NaN,NaN,7.65,8.64,NaN,NaN,--
1998-03-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-03-25,--,--,8.10,NaN,8.75,9.31,6.32,7.13,9.00,9.72,...,5.04,NaN,NaN,NaN,NaN,7.02,7.92,NaN,NaN,--
1998-07-01,--,--,6.40,NaN,6.88,7.21,5.91,6.24,7.11,7.65,...,4.05,NaN,4.32,NaN,NaN,6.57,6.93,NaN,NaN,--
1998-12-07,--,--,5.99,NaN,6.48,6.80,5.51,5.75,6.66,7.20,...,3.60,NaN,3.96,NaN,NaN,6.12,6.39,NaN,NaN,--
1999-06-10,4.59,4.14,5.35,NaN,5.43,5.59,5.02,5.26,5.94,6.03,...,2.97,NaN,2.16,NaN,NaN,5.58,5.85,NaN,NaN,--
2001-09-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-02-21,4.05,3.60,4.94,NaN,5.02,5.18,4.54,4.78,5.49,5.58,...,2.43,4.68,2.97,--,NaN,5.04,5.31,18.00,7.56,--
2003-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,--,--,NaN
2004-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-10-29,4.23,3.78,5.18,NaN,5.26,5.51,4.70,5.02,5.76,5.85,...,2.70,4.68,NaN,--,NaN,5.22,5.58,NaN,NaN,--
2005-03-17,NaN,NaN,NaN,5.22,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-04-28,4.59,4.14,5.43,NaN,5.51,5.75,4.86,5.26,6.03,6.12,...,2.97,4.68,NaN,--,NaN,5.40,5.85,NaN,NaN,--
2006-08-19,4.59,4.14,5.67,NaN,5.83,6.16,5.02,5.51,6.30,6.48,...,3.24,4.68,NaN,--,NaN,5.58,6.12,NaN,NaN,--
2007-03-18,4.77,4.32,5.91,NaN,6.08,6.40,5.10,5.75,6.57,6.75,...,3.51,4.68,NaN,--,NaN,5.67,6.39,NaN,NaN,--
2007-05-19,4.86,4.41,6.08,NaN,6.24,6.48,5.26,5.91,6.75,6.93,...,3.69,4.68,NaN,--,NaN,5.85,6.57,NaN,NaN,--
2007-07-21,4.95,4.50,6.32,NaN,6.48,6.64,5.43,6.16,7.02,7.20,...,3.96,NaN,NaN,NaN,NaN,6.03,6.84,NaN,NaN,--
2007-08-22,5.04,4.59,6.48,NaN,6.64,6.80,5.59,6.32,7.20,7.38,...,4.14,NaN,NaN,NaN,NaN,6.21,7.02,NaN,NaN,--
2007-09-15,5.22,4.77,6.72,NaN,6.88,7.05,5.83,6.56,7.47,7.65,...,4.41,NaN,NaN,NaN,NaN,6.48,7.29,NaN,NaN,--
2007-12-21,5.22,4.77,6.80,NaN,6.97,7.05,5.91,6.72,7.56,7.74,...,4.59,NaN,NaN,NaN,NaN,6.57,7.47,NaN,NaN,--
2008-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-16,5.13,4.59,6.56,NaN,6.80,6.97,5.59,6.48,7.29,7.56,...,4.32,NaN,NaN,NaN,NaN,6.21,7.20,NaN,NaN,--
2008-10-09,4.86,4.32,6.32,NaN,6.56,6.72,5.51,6.24,7.02,7.29,...,4.05,NaN,NaN,NaN,NaN,6.12,6.93,NaN,NaN,--
2008-10-30,4.59,4.05,6.08,NaN,6.32,6.48,5.43,5.99,6.75,7.02,...,3.78,NaN,NaN,NaN,NaN,6.03,6.66,NaN,NaN,--
2008-11-27,4.05,3.51,5.10,NaN,5.35,5.51,4.54,5.02,5.67,5.94,...,2.70,NaN,2.97,NaN,NaN,5.04,5.58,NaN,NaN,--
2008-12-23,3.87,3.33,4.86,NaN,5.18,5.35,4.37,4.78,5.40,5.76,...,2.43,NaN,1.80,NaN,NaN,4.86,5.31,NaN,NaN,--
2010-10-20,4.05,3.50,5.04,NaN,5.36,5.53,4.59,5.00,5.60,5.96,...,2.68,NaN,NaN,NaN,NaN,5.10,5.56,NaN,NaN,--
2010-12-26,4.30,3.75,5.26,NaN,5.60,5.76,4.82,5.23,5.85,6.22,...,2.93,NaN,2.25,NaN,NaN,5.35,5.81,NaN,NaN,--
2011-02-09,4.50,4.00,5.49,NaN,5.80,5.94,5.04,5.45,6.10,6.45,...,3.18,NaN,NaN,NaN,NaN,5.60,6.06,NaN,NaN,--
2011-04-06,4.70,4.20,5.76,NaN,5.99,6.12,5.26,5.68,6.40,6.65,...,3.18,NaN,NaN,NaN,NaN,5.85,6.31,NaN,NaN,--
2011-07-07,4.90,4.45,5.99,NaN,6.21,6.34,5.49,5.90,6.65,6.90,...,3.18,NaN,NaN,NaN,NaN,6.10,6.56,NaN,NaN,--
2012-06-08,4.70,4.20,5.76,NaN,5.99,6.12,5.26,5.68,6.40,6.65,...,3.18,NaN,NaN,NaN,NaN,5.85,6.31,NaN,NaN,--
2012-07-06,4.50,4.00,5.54,NaN,5.76,5.89,5.04,5.40,6.15,6.40,...,--,NaN,NaN,NaN,NaN,5.60,6.00,NaN,NaN,--
2014-11-22,4.25,3.75,5.40,NaN,5.40,5.54,5.04,5.04,6.00,6.00,...,--,NaN,NaN,NaN,NaN,5.60,5.60,NaN,NaN,--
2015-03-01,4.00,3.50,5.17,NaN,5.17,5.31,4.82,4.82,5.75,5.75,...,--,NaN,NaN,NaN,NaN,5.35,5.35,NaN,NaN,--
2015-05-11,3.75,3.25,4.95,NaN,4.95,5.08,4.59,4.59,5.50,5.50,...,--,NaN,NaN,NaN,NaN,5.10,5.10,NaN,NaN,--
2015-06-28,3.50,3.00,4.72,NaN,4.72,4.86,4.37,4.37,5.25,5.25,...,--,NaN,NaN,NaN,NaN,4.85,4.85,NaN,NaN,--
2015-08-26,3.25,2.75,4.50,NaN,4.50,4.63,4.14,4.14,5.00,5.00,...,--,NaN,NaN,NaN,NaN,4.60,4.60,NaN,NaN,--
2015-09-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-10-24,3.25,2.75,4.28,NaN,4.28,4.41,3.92,3.92,4.75,4.75,...,--,NaN,NaN,NaN,NaN,4.35,4.35,NaN,NaN,--

In [96]:
final = final.merge(loan_rate_pivoted, how='left', left_on='Date', right_index=True)

In [73]:
# China - RRR

rrr = ts.get_rrr()
rrr

          date before    now changed
0   2018-10-15  15.00  14.00   -1.00
1   2018-07-05  15.50  15.00   -0.50
2   2018-04-25  16.50  15.50   -1.00
3   2016-03-01  17.00  16.50   -0.50
4   2015-10-24  17.50  17.00   -0.50
5   2015-09-06  18.00  17.50   -0.50
6   2015-06-28  18.50  18.00   -0.50
7   2015-04-20  19.50  18.50   -1.00
8   2015-02-05  20.00  19.50   -0.50
9   2012-05-18  20.50  20.00   -0.50
10  2012-02-24  21.00  20.50   -0.50
11  2011-12-05  21.50  21.00   -0.50
12  2011-06-20  21.00  21.50    0.50
13  2011-05-18  20.50  21.00    0.50
14  2011-04-21  20.00  20.50    0.50
15  2011-03-25  19.50  20.00    0.50
16  2011-02-24  19.00  19.50    0.50
17  2011-01-20  18.50  19.00    0.50
18  2010-12-20  18.00  18.50    0.50
19  2010-11-29  17.50  18.00    0.50
20  2010-11-16  17.00  17.50    0.50
21  2010-05-10  16.50  17.00    0.50
22  2010-02-25  16.00  16.50    0.50
23  2010-01-18  15.50  16.00    0.50
24  2008-12-25  16.00  15.50   -0.50
25  2008-12-05  17.00  16.00   -1.00
26  2008-10-15  17.50  17.00   -0.50
27  2008-09-25  17.50  17.50    0.00
28  2008-06-25  17.00  17.50    0.50
29  2008-06-15  16.50  17.00    0.50
30  2008-05-20  16.00  16.50    0.50
31  2008-04-25  15.50  16.00    0.50
32  2008-03-25  15.00  15.50    0.50
33  2008-01-25  14.50  15.00    0.50
34  2007-12-25  13.50  14.50    1.00
35  2007-11-26  13.00  13.50    0.50
36  2007-10-25  12.50  13.00    0.50
37  2007-09-25  12.00  12.50    0.50
38  2007-08-15  11.50  12.00    0.50
39  2007-06-05  11.00  11.50    0.50
40  2007-05-15  10.50  11.00    0.50
41  2007-04-16  10.00  10.50    0.50
42  2007-02-25   9.50  10.00    0.50
43  2007-01-15   9.00   9.50    0.50
44  2006-11-15   8.50   9.00    0.50
45  2006-08-15   8.00   8.50    0.50
46  2006-07-05   7.50   8.00    0.50
47  2004-04-25   7.00   7.50    0.50
48  2003-09-21   6.00   7.00    1.00
49  1999-11-21   8.00   6.00   -2.00
50  1998-03-21  13.00   8.00   -5.00
51  1988-09-30  12.00  13.00    1.00
52  1987-12-31  10.00  12.00    2.00
53  1985-12-31     --  10.00      --

In [74]:
rrr.columns = 'RRR_' + rrr.columns

In [76]:
final = final.merge(rrr, how='left', left_on='Date', right_on='RRR_date')
final.drop(columns=['RRR_date'], inplace=True)

In [77]:
final

,Date,GDP Growth Rate,CPI,PPI_ppiip,PPI_ppi,PPI_qm,PPI_rmi,PPI_pi,PPI_cg,PPI_food,PPI_clothing,PPI_roeu,PPI_dcg,RRR_before,RRR_now,RRR_changed
0,2013-01-01,1.9,102.03,98.36,97.63,95.03,97.8,97.82,100.68,101.28,101.54,100.93,99.02,NaN,NaN,NaN
1,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2013-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2013-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2013-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2013-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2013-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2013-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2013-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2013-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2013-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2013-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2013-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2013-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2013-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2013-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2013-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2013-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2013-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2013-01-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2013-01-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2013-01-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2013-01-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2013-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2013-01-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2130,2018-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2131,2018-11-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2132,2018-11-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2133,2018-11-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2134,2018-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2135,2018-11-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2136,2018-11-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2137,2018-11-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2138,2018-11-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2139,2018-11-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2140,2018-11-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,2018-11-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2142,2018-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2143,2018-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2144,2018-11-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2145,2018-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2146,2018-11-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2147,2018-11-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2148,2018-11-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2149,2018-11-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2150,2018-11-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2151,2018-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2152,2018-11-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2153,2018-11-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2154,2018-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2155,2018-11-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2156,2018-11-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2157,2018-11-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2158,2018-11-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2159,2018-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
# China - Money Supply

money_supply = ts.get_money_supply()
money_supply

,month,m2,m2_yoy,m1,m1_yoy,m0,m0_yoy,cd,cd_yoy,qm,qm_yoy,ftd,ftd_yoy,sd,sd_yoy,rests,rests_yoy
0,2018.10,1795561.60,8.00,540128.37,2.70,70106.62,2.80,470021.74,--,1255433.23,--,340815.59,--,702827.46,--,211790.18,--
1,2018.9,1801665.58,8.30,538574.08,4.00,71254.26,2.20,467319.82,--,1263091.50,--,349826.79,--,706256.25,--,207008.46,--
2,2018.8,1788670.43,8.20,538324.64,3.90,69775.39,3.30,468549.25,--,1250345.79,--,341834.17,--,692847.93,--,215663.69,--
3,2018.7,1776196.11,8.50,536624.29,5.10,69530.59,3.60,467093.70,--,1239571.81,--,335935.49,--,689397.13,--,214239.19,--
4,2018.6,1770178.37,8.30,543944.71,6.00,69589.33,3.60,474355.38,--,1226233.66,--,334425.29,--,692440.77,--,199367.60,--
5,2018.5,1743063.79,8.30,526276.72,6.00,69774.81,3.60,456501.91,--,1216787.08,--,336063.23,--,681333.90,--,199389.95,--
6,2018.4,1737683.73,8.30,525447.77,7.20,71476.46,4.50,453971.31,--,1212235.96,--,335348.35,--,679185.94,--,197701.67,--
7,2018.3,1739859.48,8.20,523540.07,7.10,72692.63,6.00,450847.45,--,1216319.40,--,332605.89,--,692563.69,--,191149.82,--
8,2018.2,1729070.12,8.80,517035.99,8.50,81424.24,13.50,435611.75,--,1212034.13,--,330531.73,--,687076.39,--,194426.00,--
9,2018.1,1720814.46,8.62,543247.13,14.97,74636.29,-13.81,468610.84,--,1177567.33,--,328169.80,--,658424.25,--,190973.27,--
10,2017.12,1676768.54,8.10,543790.15,11.80,70645.60,3.40,473144.55,--,1132978.39,--,320196.23,--,649341.50,--,163440.66,--
11,2017.11,1670013.40,9.10,535565.05,12.70,68623.16,5.70,466941.89,--,1134448.35,--,320651.87,--,641619.60,--,172176.88,--
12,2017.10,1653434.16,8.90,525977.19,13.00,68230.69,6.30,457746.50,--,1127456.97,--,319740.97,--,640250.93,--,167465.07,--
13,2017.9,1655662.07,9.00,517863.04,14.00,69748.54,7.20,448114.50,--,1137799.03,--,326614.31,--,648349.70,--,162835.01,--
14,2017.8,1645156.60,8.60,518113.93,14.00,67550.99,6.50,450562.94,--,1127042.67,--,317888.57,--,637886.94,--,171267.16,--
15,2017.7,1628996.63,8.90,510484.58,15.30,67129.04,6.10,443355.54,--,1118512.05,--,314699.58,--,635229.77,--,168582.71,--
16,2017.6,1631282.53,9.10,510228.17,15.00,66977.68,6.60,443250.48,--,1121054.36,--,317003.07,--,642931.90,--,161119.39,--
17,2017.5,1601360.42,9.10,496389.78,17.00,67333.21,7.30,429056.58,--,1104970.63,--,314929.83,--,632225.70,--,157815.10,--
18,2017.4,1596331.87,9.80,490180.42,18.54,68392.60,6.19,421787.82,--,1106151.45,--,318092.78,--,630992.53,--,157066.14,--
19,2017.3,1599609.57,10.10,488770.09,18.80,68605.05,6.10,420165.04,--,1110839.48,--,317183.42,--,643278.44,--,150377.62,--
20,2017.2,1582913.07,10.40,476527.60,21.40,71727.69,3.30,404799.91,--,1106385.48,--,311667.58,--,635880.32,--,158837.59,--
21,2017.1,1575945.59,10.70,472526.45,14.50,86598.61,19.40,385927.84,--,1103419.14,--,317957.26,--,634745.73,--,150716.15,--
22,2016.12,1550066.67,11.33,486557.24,21.35,68303.87,8.05,418253.37,--,1063509.43,--,307989.61,--,603504.20,--,152015.62,--
23,2016.11,1530432.06,11.39,475405.54,22.65,64903.50,7.58,410502.04,--,1055026.52,--,309067.58,--,597374.12,--,148584.82,--
24,2016.10,1519485.40,11.64,465446.65,23.85,64214.93,7.20,401231.71,--,1054038.76,--,307895.68,--,594169.86,--,151973.22,--
25,2016.9,1516360.50,11.50,454340.25,24.70,65068.62,6.60,389271.63,--,1062020.26,--,315077.15,--,598880.53,--,148062.57,--
26,2016.8,1510982.91,11.35,454543.60,25.29,63454.70,7.44,391088.90,--,1056439.31,--,307806.49,--,589372.14,--,159260.68,--
27,2016.7,1491558.72,10.22,442934.43,25.43,63276.01,7.23,379658.42,--,1048624.29,--,301688.23,--,585217.87,--,161718.19,--
28,2016.6,1490491.83,11.78,443643.70,24.59,62818.89,7.19,380824.81,--,1046848.13,--,301673.99,--,587548.66,--,157625.48,--
29,2016.5,1461695.11,11.81,424250.70,23.66,62780.71,6.27,361469.99,--,1037444.41,--,302474.13,--,577996.21,--,156974.07,--
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,1980.6,--,--,983.04,20.67,243.30,16.57,--,--,--,--,--,--,--,--,--,--
461,1980.5,--,--,957.20,18.30,243.13,16.33,--,--,--,--,--,--,--,--,--,--
462,1980.4,--,--,954.89,14.35,254.07,16.91,--,--,--,--,--,--,--,--,--,--
463,1980.3,--,--,963.91,15.68,261.49,19.39,--,--,--,--,--,--,--,--,--,--
464,1980.2,--,--,975.80,18.57,279.18,22.25,--,--,--,--,--,--,--,--,--,--
465,1980.1,--,--,1031.89,21.20,300.41,16.79,--,--,--,--,--,--,--,--,--,--
466,1979.12,--,--,1069.36,24.42,267.71,26.26,--,--,--,--,--,--,--,--,--,--
467,1979.11,--,--,955.66,18.24,235.13,23.40,--,--,--,--,--,--,--,--,--,--
468,1979.10,--,--,895.32,14.99,220.90,19.25,--,--,--,--,--,--,--,--,--,--
469,1979.9,--,--,871.19,14.11,225.57,19.81,--,--,--,--,--,--,--,--,--,--
470,1979.8,--,--,849.58,12.38,215.35,18.25,--,--,--,--,--,--,--,--,--,--
471,1979.7,--,--,831.28,11.37,212.96,17.64,--,--,--,--,--,--,--,--,--,--
472,1979.6,--,--,814.67,9.34,208.71,16.95,--,--,--,--,--,--,--,--,--,--
473,1979.5,--,--,809.14,6.76,209.00,14.73,--,--,--,--,--,--,--,--,--,--
474,1979.4,--,--,835.08,3.33,217.33,12.82,--,--,--,--,--,--,--,--,--,--
475,1979.3,--,--,833.24,0.65,219.02,12.40,--,--,--,--,--,--,--,--,--,--
476,1979.2,--,--,823.00,-1.24,228.36,10.91,--,--,--,--,--,--,--,--,--,--
477,1979.1,--,--,851.39,-2.20,257.22,12.03,--,--,--,--,--,--,--,--,--,--
478,1978.12,--,--,859.45,--,212.03,--,--,--,--,--,--,--,--,--,--,--
479,1978.11,--,--,808.27,--,190.54,--,--,--,--,--,--,--,--,--,--,--
480,1978.10,--,--,778.64,--,185.24,--,--,--,--,--,--,--,--,--,--,--
481,1978.9,--,--,763.47,--,188.27,--,--,--,--,--,--,--,--,--,--,--
482,1978.8,--,--,755.99,--,182.12,--,--,--,--,--,--,--,--,--,--,--
483,1978.7,--,--,746.43,--,181.02,--,--,--,--,--,--,--,--,--,--,--
484,1978.6,--,--,745.08,--,178.46,--,--,--,--,--,--,--,--,--,--,--
485,1978.5,--,--,757.93,--,182.17,--,--,--,--,--,--,--,--,--,--,--
486,1978.4,--,--,808.17,--,192.63,--,--,--,--,--,--,--,--,--,--,--
487,1978.3,--,--,827.83,--,194.86,--,--,--,--,--,--,--,--,--,--,--
488,1978.2,--,--,833.35,--,205.89,--,--,--,--,--,--,--,--,--,--,--
489,1978.1,--,--,870.53,--,229.59,--,--,--,--,--,--,--,--,--,--,--

In [79]:
date_money_supply = money_supply.month.apply(month_to_date)
money_supply['Date'] = date_money_supply
money_supply.drop(columns=['month'], inplace=True)

In [81]:
money_supply.columns = 'MS_' + money_supply.columns

In [82]:
final = final.merge(money_supply, how='left', left_on='Date', right_on='MS_Date')
final.drop(columns=['MS_Date'], inplace=True)

In [99]:
# U.S. - SP500

sp500 = pd.read_csv('SP500.csv')

In [100]:
sp500.tail(10)

             Date     Open     High      Low    Close       Volume
37811  2018-11-09  2794.10  2794.10  2764.24  2781.01  659956477.0
37812  2018-11-12  2773.93  2775.99  2722.00  2726.22  630070307.0
37813  2018-11-13  2730.05  2754.60  2714.98  2722.18  610281337.0
37814  2018-11-14  2737.90  2746.80  2685.75  2701.58  704285465.0
37815  2018-11-15  2693.52  2735.38  2670.75  2730.20  695330012.0
37816  2018-11-16  2718.54  2746.75  2712.16  2736.27  838188083.0
37817  2018-11-19  2730.74  2733.16  2681.09  2690.73  688894394.0
37818  2018-11-20  2654.60  2669.44  2631.52  2641.89  760763750.0
37819  2018-11-21  2657.74  2670.73  2649.82  2649.93  552735153.0
37820  2018-11-23  2633.36  2647.55  2631.09  2632.56          NaN

In [106]:
sp500.columns = 'SP500_' + sp500.columns

In [108]:
final = final.merge(sp500, how='left', left_on='Date', right_on='SP500_Date')

In [110]:
final.drop(columns=['SP500_Date'], inplace=True)

In [127]:
# U.S. - U.S. Stock

us_stock = pd.read_csv('stock_cpi_rf_cape.csv', dtype={'Date': str})

In [131]:
us_stock.tail(5)

,Date,P,D,E,CPI,Fraction,Rate GS10,Price,Dividend,Earnings,CAPE
1770,2018.07,2793.64,51.44,NaN,252.006,2018.54,2.89,2800.88,51.57,NaN,31.89
1771,2018.08,2857.82,51.89,NaN,252.146,2018.62,2.89,2863.63,52.00,NaN,32.50
1772,2018.09,2901.50,52.34,NaN,252.439,2018.71,3.00,2904.03,52.39,NaN,32.86
1773,2018.1,2785.46,NaN,NaN,252.586,2018.79,3.15,2786.27,NaN,NaN,31.42
1774,2018.11,2723.06,NaN,NaN,252.659,2018.87,3.22,2723.06,NaN,NaN,30.57

In [132]:
def month_to_date_for_us_stock(series):
    temp = series.split('.')
    if temp[1] == '1':
        return temp[0] + '-10-01'
    else:
        return temp[0] + '-' + temp[1] + '-01'

In [133]:
date_us_stock = us_stock.Date.apply(month_to_date_for_us_stock)
us_stock['Date'] = date_us_stock

In [135]:
us_stock.columns = 'US_Stock_' + us_stock.columns
final = final.merge(us_stock, how='left', left_on='Date', right_on='US_Stock_Date')

In [138]:
final.drop(columns=['US_Stock_Date'], inplace=True)

In [141]:
# U.S. - Trump Tweets Sentiment Analysis

sa = pd.read_csv('Trump Tweets Cleaned.csv')

In [143]:
sa = sa[['created_at', 'Sentiment - (1 for pos, -1 for neg)']]

In [144]:
sa

         created_at  Sentiment - (1 for pos, -1 for neg)
0    11/13/18 13:07                                   -1
1    11/13/18 11:50                                   -1
2    11/12/18 12:21                                   -1
3    11/12/18 12:10                                   -1
4    11/12/18 12:03                                   -1
5     11/9/18 21:10                                   -1
6     11/7/18 11:21                                    1
7     11/1/18 14:09                                    1
8    10/29/18 12:28                                    1
9    10/25/18 13:57                                   -1
10   10/23/18 16:43                                   -1
11   10/18/18 23:49                                    1
12   10/18/18 11:45                                   -1
13    10/3/18 14:02                                    1
14    10/3/18 13:04                                    1
15    10/2/18 15:02                                    1
16    10/1/18 10:40                                    1
17    10/1/18 10:30                                    1
18    9/26/18 17:26                                   -1
19    9/24/18 21:46                                    1
20    9/24/18 20:44                                    1
21    9/23/18 20:52                                    1
22    9/18/18 12:55                                   -1
23    9/18/18 12:50                                   -1
24    9/13/18 14:15                                   -1
25     9/9/18 14:01                                   -1
26     9/8/18 15:45                                   -1
27     9/8/18 14:44                                   -1
28     9/3/18 11:28                                   -1
29      9/2/18 1:23                                   -1
..              ...                                  ...
482    3/8/13 19:46                                   -1
483    3/4/13 20:10                                   -1
484    3/2/13 13:17                                   -1
485   2/28/13 21:45                                   -1
486   2/27/13 20:46                                    1
487    2/26/13 2:54                                   -1
488   2/25/13 21:13                                   -1
489   2/25/13 19:27                                   -1
490   2/21/13 20:35                                   -1
491   2/19/13 21:35                                   -1
492    2/7/13 21:24                                   -1
493    2/6/13 19:45                                   -1
494    2/4/13 21:38                                   -1
495    2/4/13 21:35                                   -1
496   1/30/13 21:28                                   -1
497   1/29/13 18:40                                   -1
498   1/24/13 20:12                                   -1
499   1/23/13 19:29                                   -1
500   1/15/13 21:32                                   -1
501   1/15/13 17:05                                    1
502   1/15/13 16:39                                   -1
503   1/15/13 16:04                                   -1
504    1/9/13 21:00                                   -1
505    1/7/13 21:03                                   -1
506  12/20/12 20:51                                   -1
507  12/12/12 20:16                                   -1
508  12/11/12 17:45                                   -1
509  12/10/12 20:45                                   -1
510  12/10/12 20:32                                   -1
511  12/10/12 20:30                                   -1

[512 rows x 2 columns]

In [150]:
date_sa = pd.to_datetime(sa.created_at).dt.strftime('%Y-%m-%d')

0      2018-11-13
1      2018-11-13
2      2018-11-12
3      2018-11-12
4      2018-11-12
5      2018-11-09
6      2018-11-07
7      2018-11-01
8      2018-10-29
9      2018-10-25
10     2018-10-23
11     2018-10-18
12     2018-10-18
13     2018-10-03
14     2018-10-03
15     2018-10-02
16     2018-10-01
17     2018-10-01
18     2018-09-26
19     2018-09-24
20     2018-09-24
21     2018-09-23
22     2018-09-18
23     2018-09-18
24     2018-09-13
25     2018-09-09
26     2018-09-08
27     2018-09-08
28     2018-09-03
29     2018-09-02
          ...
482    2013-03-08
483    2013-03-04
484    2013-03-02
485    2013-02-28
486    2013-02-27
487    2013-02-26
488    2013-02-25
489    2013-02-25
490    2013-02-21
491    2013-02-19
492    2013-02-07
493    2013-02-06
494    2013-02-04
495    2013-02-04
496    2013-01-30
497    2013-01-29
498    2013-01-24
499    2013-01-23
500    2013-01-15
501    2013-01-15
502    2013-01-15
503    2013-01-15
504    2013-01-09
505    2013-01-07
506    2012-12-20
507    2012-12-12
508    2012-12-11
509    2012-12-10
510    2012-12-10
511    2012-12-10
Name: created_at, Length: 512, dtype: object

In [151]:
sa['Date'] = date_sa
sa

/Users/zexi_ye/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

         created_at  Sentiment - (1 for pos, -1 for neg)        Date
0    11/13/18 13:07                                   -1  2018-11-13
1    11/13/18 11:50                                   -1  2018-11-13
2    11/12/18 12:21                                   -1  2018-11-12
3    11/12/18 12:10                                   -1  2018-11-12
4    11/12/18 12:03                                   -1  2018-11-12
5     11/9/18 21:10                                   -1  2018-11-09
6     11/7/18 11:21                                    1  2018-11-07
7     11/1/18 14:09                                    1  2018-11-01
8    10/29/18 12:28                                    1  2018-10-29
9    10/25/18 13:57                                   -1  2018-10-25
10   10/23/18 16:43                                   -1  2018-10-23
11   10/18/18 23:49                                    1  2018-10-18
12   10/18/18 11:45                                   -1  2018-10-18
13    10/3/18 14:02                                    1  2018-10-03
14    10/3/18 13:04                                    1  2018-10-03
15    10/2/18 15:02                                    1  2018-10-02
16    10/1/18 10:40                                    1  2018-10-01
17    10/1/18 10:30                                    1  2018-10-01
18    9/26/18 17:26                                   -1  2018-09-26
19    9/24/18 21:46                                    1  2018-09-24
20    9/24/18 20:44                                    1  2018-09-24
21    9/23/18 20:52                                    1  2018-09-23
22    9/18/18 12:55                                   -1  2018-09-18
23    9/18/18 12:50                                   -1  2018-09-18
24    9/13/18 14:15                                   -1  2018-09-13
25     9/9/18 14:01                                   -1  2018-09-09
26     9/8/18 15:45                                   -1  2018-09-08
27     9/8/18 14:44                                   -1  2018-09-08
28     9/3/18 11:28                                   -1  2018-09-03
29      9/2/18 1:23                                   -1  2018-09-02
..              ...                                  ...         ...
482    3/8/13 19:46                                   -1  2013-03-08
483    3/4/13 20:10                                   -1  2013-03-04
484    3/2/13 13:17                                   -1  2013-03-02
485   2/28/13 21:45                                   -1  2013-02-28
486   2/27/13 20:46                                    1  2013-02-27
487    2/26/13 2:54                                   -1  2013-02-26
488   2/25/13 21:13                                   -1  2013-02-25
489   2/25/13 19:27                                   -1  2013-02-25
490   2/21/13 20:35                                   -1  2013-02-21
491   2/19/13 21:35                                   -1  2013-02-19
492    2/7/13 21:24                                   -1  2013-02-07
493    2/6/13 19:45                                   -1  2013-02-06
494    2/4/13 21:38                                   -1  2013-02-04
495    2/4/13 21:35                                   -1  2013-02-04
496   1/30/13 21:28                                   -1  2013-01-30
497   1/29/13 18:40                                   -1  2013-01-29
498   1/24/13 20:12                                   -1  2013-01-24
499   1/23/13 19:29                                   -1  2013-01-23
500   1/15/13 21:32                                   -1  2013-01-15
501   1/15/13 17:05                                    1  2013-01-15
502   1/15/13 16:39                                   -1  2013-01-15
503   1/15/13 16:04                                   -1  2013-01-15
504    1/9/13 21:00                                   -1  2013-01-09
505    1/7/13 21:03                                   -1  2013-01-07
506  12/20/12 20:51                                   -1  2012-12-20
507  12/12/12 20:16                                   -1  2012-12-12
508  12/11/12 17:45                                   -1  2012-12-11
509  12/10/12 20:45                                   -1  2012-12-10
510  12/10/12 20:32                                   -1  2012-12-10
511  12/10/12 20:30                                   -1  2012-12-10

[512 rows x 3 columns]

In [152]:
sa.drop(columns=['created_at'], inplace=True)

/Users/zexi_ye/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3694: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [154]:
sa.drop_duplicates(subset='Date', inplace=True)

/Users/zexi_ye/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [156]:
final = final.merge(sa, how='left', on='Date')

In [157]:
final

,Date,GDP Growth Rate,CPI,PPI_ppiip,PPI_ppi,PPI_qm,PPI_rmi,PPI_pi,PPI_cg,PPI_food,...,US_Stock_D,US_Stock_E,US_Stock_CPI,US_Stock_Fraction,US_Stock_Rate GS10,US_Stock_Price,US_Stock_Dividend,US_Stock_Earnings,US_Stock_CAPE,"Sentiment - (1 for pos, -1 for neg)"
0,2013-01-01,1.9,102.03,98.36,97.63,95.03,97.8,97.82,100.68,101.28,...,31.54,86.91,230.280,2013.04,1.91,1624.27,34.6,95.35,21.90,NaN
1,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2013-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
7,2013-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2013-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
9,2013-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2013-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2013-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2013-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2013-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2013-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
15,2013-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2013-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2013-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2013-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2013-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2013-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2013-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
23,2013-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
24,2013-01-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2013-01-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2013-01-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2013-01-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2013-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
29,2013-01-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2130,2018-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,252.659,2018.87,3.22,2723.06,NaN,NaN,30.57,1.0
2131,2018-11-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2132,2018-11-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2133,2018-11-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2134,2018-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2135,2018-11-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2136,2018-11-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2137,2018-11-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2138,2018-11-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
2139,2018-11-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2140,2018-11-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,2018-11-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
2142,2018-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
2143,2018-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2144,2018-11-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2145,2018-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2146,2018-11-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2147,2018-11-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2148,2018-11-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2149,2018-11-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2150,2018-11-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2151,2018-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2152,2018-11-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2153,2018-11-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2154,2018-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2155,2018-11-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2156,2018-11-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2157,2018-11-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2158,2018-11-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2159,2018-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [158]:
final.iloc[0, -1] = -1

In [161]:
final.to_csv('Date Aligned Misc Features.csv', index=False)